language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"

env:
  - DJANGO_VERSION=1.4.15
  - DJANGO_VERSION=1.5.10
  - DJANGO_VERSION=1.6.7
  - DJANGO_VERSION=1.7

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.7
  include:
    - python: "3.4"
      env: DJANGO_VERSION=1.7

install:
  - pip install --download-cache=".pip_download_cache" -q Django==$DJANGO_VERSION
  - pip install --download-cache=".pip_download_cache" -r req/tests.txt
  - python setup.py -q install

script:
  - cd examples/django_rest_framework/backend/
  - bash load.sh &
  - sleep 4  # wait for runserver init
  - cd ../frontend/
  - python manage.py test frontend
